MODEL_TYPE_NORMAL = 0
MODEL_TYPE_HIERARCHY = 1
MODEL_TYPE_SKELETON = 2
MODEL_TYPE_ANIMATED = 3
MODEL_TYPE_SKINNED = 4
MODEL_TYPE_SKINNED_MESH = 5
MODEL_TYPE_SOFT_BODY = 8

MODEL_VF_STATIC = 2
MODEL_VF_LEVEL = 3

MODEL_VER_2033 = 7
MODEL_VER_LL = 21
MODEL_VER_REDUX = 23
MODEL_VER_ARCTIC = 34
MODEL_VER_EXODUS = 44

MODEL_CHUNK_HEADER = 1
MODEL_CHUNK_TEXTURE = 2
MODEL_CHUNK_VERTICES = 3
MODEL_CHUNK_INDICES = 4
MODEL_CHUNK_CHILD = 9
MODEL_CHUNK_CHILD_L = 10
MODEL_CHUNK_LOD1 = 11
MODEL_CHUNK_LOD0 = 12
MODEL_CHUNK_GEOMETRY_REF = 21

MODEL_CHUNK_SKIN_VERTICES = 5
MODEL_CHUNK_SKELETON_CRC = 13
MODEL_CHUNK_MESHES = 15
MODEL_CHUNK_MESHES_FN = 16
MODEL_CHUNK_SKELETON_FN = 20
MODEL_CHUNK_SKELETON = 24
MODEL_CHUNK_PHYSX_FN = 25
MODEL_CHUNK_TEXTURE_SUBST = 29
MODEL_CHUNK_MTL_SETS = 32
MODEL_CHUNK_COMMENT = 36
